// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brdtmlcwzrmoczemalbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZHRtbGN3enJtb2N6ZW1hbGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4ODU4NzQsImV4cCI6MjA5MDQ2MTg3NH0.azDijJZBYpH6x6L7YJ5jkqJIWD2cbkUSiY2n2UD-zzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});